/*
  Mock data mirroring the real nomenclature schema.
  Used when VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are not set.
  Field names match the transformed shape returned by useMenu (post-mapping).
*/
export const MOCK_DATA = {
  categories: [
    { id: "cat-manakish", code: "MANAKISH", name: "Manakish",    sort_order: 1 },
    { id: "cat-salads",   code: "SALADS",   name: "Salads",      sort_order: 2 },
    { id: "cat-mezze",    code: "MEZZE",    name: "Mezze",       sort_order: 3 },
    { id: "cat-smoothies",code: "SMOOTHIE", name: "Smoothies",   sort_order: 4 },
    { id: "cat-juices",   code: "JUICE",    name: "Fresh Juices",sort_order: 5 },
    { id: "cat-coffee",   code: "COFFEE",   name: "Coffee",      sort_order: 6 },
  ],
  dishes: [
    {
      id: "d1", category_id: "cat-manakish", category_name: "Manakish",
      name: "Za'atar Man'oushe",
      description: "Wild thyme, sesame & olive oil on fresh-baked dough",
      price: 120, calories: 380, protein: 11, carbs: 48, fat: 16,
      portion_size: 220, portion_unit: "g",
      image_url: "/assets/menu/manakish-zaatar.png",
      is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-gluten"],
      tags: [
        { slug: "vegan",           name: "Vegan",       tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",      name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-gluten", name: "Gluten",      tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d2", category_id: "cat-manakish", category_name: "Manakish",
      name: "Halloumi & Tomato Man'oushe",
      description: "Grilled halloumi, vine tomato, mint, nigella seeds",
      price: 165, calories: 520, protein: 22, carbs: 46, fat: 28,
      portion_size: 280, portion_unit: "g",
      image_url: "/assets/menu/manakish-cheese-olive.png",
      is_featured: true,
      diets: ["vegetarian", "high-protein"],
      allergens: ["contains-gluten", "contains-dairy"],
      tags: [
        { slug: "vegetarian",      name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "high-protein",    name: "High protein",tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-gluten", name: "Gluten",      tag_group: "allergen",color: "#D2A24A" },
        { slug: "contains-dairy",  name: "Dairy",       tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Bestseller", tone: "solid-spice" }],
    },
    {
      id: "d3", category_id: "cat-manakish", category_name: "Manakish",
      name: "Sujuk & Egg Man'oushe",
      description: "Spiced beef sujuk, free-range egg, pickled chilli",
      price: 190, calories: 610, protein: 28, carbs: 44, fat: 35,
      portion_size: 290, portion_unit: "g",
      image_url: "/assets/menu/manakish-beef.png", is_featured: false,
      diets: ["high-protein"],
      allergens: ["contains-gluten", "contains-egg"],
      tags: [
        { slug: "high-protein",  name: "High protein",tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-gluten",name: "Gluten",     tag_group: "allergen",color: "#D2A24A" },
        { slug: "contains-egg",  name: "Egg",         tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Spicy", tone: "spice" }],
    },
    {
      id: "d4", category_id: "cat-salads", category_name: "Salads",
      name: "Halloumi & Avocado Bowl",
      description: "Grilled halloumi, avocado, quinoa, pomegranate, lemon-tahini",
      price: 290, calories: 520, protein: 24, carbs: 38, fat: 30,
      portion_size: 320, portion_unit: "g",
      image_url: null, is_featured: true,
      diets: ["vegetarian", "gluten-free", "high-protein"],
      allergens: ["contains-dairy", "contains-nuts"],
      tags: [
        { slug: "vegetarian",    name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "gluten-free",   name: "Gluten-free", tag_group: "diet",    color: "#A6BE86" },
        { slug: "high-protein",  name: "High protein",tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-dairy",name: "Dairy",       tag_group: "allergen",color: "#D2A24A" },
        { slug: "contains-nuts", name: "Nuts",        tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Bestseller", tone: "solid-spice" }],
    },
    {
      id: "d5", category_id: "cat-salads", category_name: "Salads",
      name: "Fattoush",
      description: "Crisp romaine, sumac, mint, toasted pita & pomegranate dressing",
      price: 210, calories: 240, protein: 6, carbs: 28, fat: 12,
      portion_size: 260, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-gluten"],
      tags: [
        { slug: "vegan",          name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-gluten",name: "Gluten",    tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d6", category_id: "cat-salads", category_name: "Salads",
      name: "Tabbouleh",
      description: "Parsley, bulgur, tomato, mint, lemon & cold-pressed olive oil",
      price: 180, calories: 190, protein: 5, carbs: 26, fat: 8,
      portion_size: 220, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-gluten"],
      tags: [
        { slug: "vegan",          name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-gluten",name: "Gluten",    tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d7", category_id: "cat-mezze", category_name: "Mezze",
      name: "Hummus Beiruti",
      description: "Whipped chickpea, tahini, garlic, cumin & warm flatbread",
      price: 160, calories: 320, protein: 10, carbs: 30, fat: 18,
      portion_size: 180, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-gluten", "contains-nuts"],
      tags: [
        { slug: "vegan",          name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-gluten",name: "Gluten",    tag_group: "allergen",color: "#D2A24A" },
        { slug: "contains-nuts",  name: "Nuts",      tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d8", category_id: "cat-mezze", category_name: "Mezze",
      name: "Muhammara",
      description: "Roasted red pepper & walnut dip, pomegranate molasses",
      price: 150, calories: 210, protein: 5, carbs: 14, fat: 15,
      portion_size: 160, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-nuts"],
      tags: [
        { slug: "vegan",        name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",   name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-nuts",name: "Nuts",      tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Chef's pick", tone: "gold" }],
    },
    {
      id: "d9", category_id: "cat-mezze", category_name: "Mezze",
      name: "Falafel (6)",
      description: "Crisp herb falafel, pickles & tahini sauce",
      price: 140, calories: 360, protein: 14, carbs: 34, fat: 18,
      portion_size: 200, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "high-protein"],
      allergens: ["contains-gluten"],
      tags: [
        { slug: "vegan",          name: "Vegan",       tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "high-protein",   name: "High protein",tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-gluten",name: "Gluten",      tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d10", category_id: "cat-smoothies", category_name: "Smoothies",
      name: "Green Glow",
      description: "Spinach, green apple, banana, lime, ginger & coconut water",
      price: 170, calories: 180, protein: 3, carbs: 38, fat: 2,
      portion_size: 350, portion_unit: "ml",
      image_url: null, is_featured: true,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: [],
      tags: [
        { slug: "vegan",       name: "Vegan",       tag_group: "diet", color: "#5B7A3D" },
        { slug: "vegetarian",  name: "Vegetarian",  tag_group: "diet", color: "#7E9C5C" },
        { slug: "gluten-free", name: "Gluten-free", tag_group: "diet", color: "#A6BE86" },
        { slug: "dairy-free",  name: "Dairy-free",  tag_group: "diet", color: "#A6BE86" },
      ],
      badges: [{ label: "Bestseller", tone: "solid-spice" }],
    },
    {
      id: "d11", category_id: "cat-smoothies", category_name: "Smoothies",
      name: "Date & Tahini Shake",
      description: "Medjool dates, tahini, banana, almond milk & cinnamon",
      price: 190, calories: 320, protein: 8, carbs: 46, fat: 12,
      portion_size: 380, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: ["contains-nuts"],
      tags: [
        { slug: "vegan",        name: "Vegan",       tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",   name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "gluten-free",  name: "Gluten-free", tag_group: "diet",    color: "#A6BE86" },
        { slug: "dairy-free",   name: "Dairy-free",  tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-nuts",name: "Nuts",        tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d12", category_id: "cat-juices", category_name: "Fresh Juices",
      name: "Pomegranate",
      description: "Cold-pressed pomegranate, nothing added",
      price: 160, calories: 150, protein: 2, carbs: 36, fat: 0,
      portion_size: 300, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: [],
      tags: [
        { slug: "vegan",      name: "Vegan",       tag_group: "diet", color: "#5B7A3D" },
        { slug: "vegetarian", name: "Vegetarian",  tag_group: "diet", color: "#7E9C5C" },
        { slug: "gluten-free",name: "Gluten-free", tag_group: "diet", color: "#A6BE86" },
        { slug: "dairy-free", name: "Dairy-free",  tag_group: "diet", color: "#A6BE86" },
      ],
      badges: [],
    },
    {
      id: "d13", category_id: "cat-juices", category_name: "Fresh Juices",
      name: "Carrot · Orange · Turmeric",
      description: "Cold-pressed carrot, orange, turmeric & black pepper",
      price: 150, calories: 130, protein: 2, carbs: 30, fat: 1,
      portion_size: 300, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: [],
      tags: [
        { slug: "vegan",      name: "Vegan",       tag_group: "diet", color: "#5B7A3D" },
        { slug: "vegetarian", name: "Vegetarian",  tag_group: "diet", color: "#7E9C5C" },
        { slug: "gluten-free",name: "Gluten-free", tag_group: "diet", color: "#A6BE86" },
        { slug: "dairy-free", name: "Dairy-free",  tag_group: "diet", color: "#A6BE86" },
      ],
      badges: [],
    },
    {
      id: "d14", category_id: "cat-coffee", category_name: "Coffee",
      name: "Cardamom Flat White",
      description: "Double ristretto, ground cardamom, silky milk",
      price: 130, calories: 120, protein: 6, carbs: 9, fat: 6,
      portion_size: 180, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegetarian"],
      allergens: ["contains-dairy"],
      tags: [
        { slug: "vegetarian",   name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-dairy",name: "Dairy",   tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Chef's pick", tone: "gold" }],
    },
    {
      id: "d15", category_id: "cat-coffee", category_name: "Coffee",
      name: "Mint Iced Latte",
      description: "Espresso, fresh mint, milk over ice",
      price: 140, calories: 110, protein: 5, carbs: 11, fat: 4,
      portion_size: 300, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegetarian"],
      allergens: ["contains-dairy"],
      tags: [
        { slug: "vegetarian",   name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-dairy",name: "Dairy",   tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
  ],
};
