/*
  Mock data mirroring the real nomenclature schema.
  Used when VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY are not set.
  Field names match the transformed shape returned by useMenu (post-mapping).
*/
export const MOCK_DATA = {
  categories: [
    { id: "cat-manakish", code: "MANAKISH", name: "Manakish",    sort_order: 1 },
    { id: "cat-salads",   code: "SALADS",   name: "Salads",      sort_order: 2 },
    { id: "cat-mezze",    code: "MEZZE",    name: "Mezze",       sort_order: 3 },
    { id: "cat-smoothies",code: "SMOOTHIE", name: "Smoothies",   sort_order: 4 },
    { id: "cat-juices",   code: "JUICE",    name: "Fresh Juices",sort_order: 5 },
    { id: "cat-coffee",   code: "COFFEE",   name: "Coffee",      sort_order: 6 },
  ],
  dishes: [
    // ---- Manakish, tiered like the shop poster (Classic 59 / Specialty 69 /
    //      Premium 79). Mirrors the live menu; used offline / in preview. ----
    ...[
      ["m-classic-1", "Za'atar", "Wild thyme, sesame & olive oil on potato-rice dough", "/assets/menu/manakish-zaatar.png"],
      ["m-classic-2", "6 Cheese", "A blend of six melting cheeses", null],
      ["m-classic-3", "Cheese & Olive", "Cheese with black olives", "/assets/menu/manakish-cheese-olive.png"],
      ["m-classic-4", "Cheese & Mushroom", "Cheese with sautéed mushrooms", null],
      ["m-classic-5", "Pumpkin & Cheese", "Roasted pumpkin & cheese mix", null],
    ].map(([id, name, description, image_url], i) => ({
      id, category_id: "cat-manakish", category_name: "Manakish", category_code: "KP-FIN-MAN",
      subcategory_id: "tier-classic", subcategory_name: "Classic", subcategory_sort: 1,
      name, description, price: 59, calories: 360, protein: 11, carbs: 44, fat: 14,
      portion_size: 220, portion_unit: "g", image_url, is_featured: i === 0,
      diets: ["vegetarian"], allergens: [], tags: [], badges: [],
    })),
    ...[
      ["m-spec-1", "Beef", "Spiced grass-fed beef", "/assets/menu/manakish-beef.png"],
      ["m-spec-2", "Lamb", "Grass-fed lamb with peppers", null],
      ["m-spec-3", "Falafel", "Crushed falafel, tahini & pomegranate", null],
      ["m-spec-4", "Cheese & Za'atar", "Za'atar with melted cheese", null],
      ["m-spec-5", "Cheese & Red Peper", "Cheese with roasted red pepper", null],
    ].map(([id, name, description, image_url]) => ({
      id, category_id: "cat-manakish", category_name: "Manakish", category_code: "KP-FIN-MAN",
      subcategory_id: "tier-signature", subcategory_name: "Signature", subcategory_sort: 2,
      name, description, price: 69, calories: 480, protein: 22, carbs: 42, fat: 24,
      portion_size: 250, portion_unit: "g", image_url, is_featured: false,
      diets: ["high-protein"], allergens: [], tags: [], badges: [],
    })),
    ...[
      ["m-prem-1", "Sojok Lamb", "Spiced grass-fed sojok lamb", null],
      ["m-prem-2", "Lamb Truffle & Mushroom", "Grass-fed lamb, truffle & mushroom", null],
      ["m-prem-3", "Pumpkin & Goat Cheese", "Roasted pumpkin & goat cheese", null],
      ["m-prem-4", "Salami Pizza", "Coming soon", null],
    ].map(([id, name, description, image_url], i) => ({
      id, category_id: "cat-manakish", category_name: "Manakish", category_code: "KP-FIN-MAN",
      subcategory_id: "tier-premium", subcategory_name: "Premium", subcategory_sort: 3,
      name, description, price: 79, calories: 560, protein: 26, carbs: 40, fat: 30,
      portion_size: 270, portion_unit: "g", image_url, is_featured: false,
      stockState: i === 3 ? "coming_soon" : "in_stock", comingSoon: i === 3,
      diets: ["high-protein"], allergens: [], tags: [], badges: [],
    })),
    {
      id: "d4", category_id: "cat-salads", category_name: "Salads",
      name: "Halloumi & Avocado Bowl",
      description: "Grilled halloumi, avocado, quinoa, pomegranate, lemon-tahini",
      price: 290, calories: 520, protein: 24, carbs: 38, fat: 30,
      portion_size: 320, portion_unit: "g",
      image_url: null, is_featured: true,
      diets: ["vegetarian", "gluten-free", "high-protein"],
      allergens: ["contains-dairy", "contains-nuts"],
      tags: [
        { slug: "vegetarian",    name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "gluten-free",   name: "Gluten-free", tag_group: "diet",    color: "#A6BE86" },
        { slug: "high-protein",  name: "High protein",tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-dairy",name: "Dairy",       tag_group: "allergen",color: "#D2A24A" },
        { slug: "contains-nuts", name: "Nuts",        tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Bestseller", tone: "solid-spice" }],
    },
    {
      id: "d5", category_id: "cat-salads", category_name: "Salads",
      name: "Fattoush",
      description: "Crisp romaine, sumac, mint, toasted pita & pomegranate dressing",
      price: 210, calories: 240, protein: 6, carbs: 28, fat: 12,
      portion_size: 260, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-gluten"],
      tags: [
        { slug: "vegan",          name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-gluten",name: "Gluten",    tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d6", category_id: "cat-salads", category_name: "Salads",
      name: "Tabbouleh",
      description: "Parsley, bulgur, tomato, mint, lemon & cold-pressed olive oil",
      price: 180, calories: 190, protein: 5, carbs: 26, fat: 8,
      portion_size: 220, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-gluten"],
      tags: [
        { slug: "vegan",          name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-gluten",name: "Gluten",    tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d7", category_id: "cat-mezze", category_name: "Mezze",
      name: "Hummus Beiruti",
      description: "Whipped chickpea, tahini, garlic, cumin & warm flatbread",
      price: 160, calories: 320, protein: 10, carbs: 30, fat: 18,
      portion_size: 180, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-gluten", "contains-nuts"],
      tags: [
        { slug: "vegan",          name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-gluten",name: "Gluten",    tag_group: "allergen",color: "#D2A24A" },
        { slug: "contains-nuts",  name: "Nuts",      tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d8", category_id: "cat-mezze", category_name: "Mezze",
      name: "Muhammara",
      description: "Roasted red pepper & walnut dip, pomegranate molasses",
      price: 150, calories: 210, protein: 5, carbs: 14, fat: 15,
      portion_size: 160, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian"],
      allergens: ["contains-nuts"],
      tags: [
        { slug: "vegan",        name: "Vegan",     tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",   name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-nuts",name: "Nuts",      tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Chef's pick", tone: "gold" }],
    },
    {
      id: "d9", category_id: "cat-mezze", category_name: "Mezze",
      name: "Falafel (6)",
      description: "Crisp herb falafel, pickles & tahini sauce",
      price: 140, calories: 360, protein: 14, carbs: 34, fat: 18,
      portion_size: 200, portion_unit: "g",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "high-protein"],
      allergens: ["contains-gluten"],
      tags: [
        { slug: "vegan",          name: "Vegan",       tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",     name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "high-protein",   name: "High protein",tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-gluten",name: "Gluten",      tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d10", category_id: "cat-smoothies", category_name: "Smoothies",
      name: "Green Glow",
      description: "Spinach, green apple, banana, lime, ginger & coconut water",
      price: 170, calories: 180, protein: 3, carbs: 38, fat: 2,
      portion_size: 350, portion_unit: "ml",
      image_url: null, is_featured: true,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: [],
      tags: [
        { slug: "vegan",       name: "Vegan",       tag_group: "diet", color: "#5B7A3D" },
        { slug: "vegetarian",  name: "Vegetarian",  tag_group: "diet", color: "#7E9C5C" },
        { slug: "gluten-free", name: "Gluten-free", tag_group: "diet", color: "#A6BE86" },
        { slug: "dairy-free",  name: "Dairy-free",  tag_group: "diet", color: "#A6BE86" },
      ],
      badges: [{ label: "Bestseller", tone: "solid-spice" }],
    },
    {
      id: "d11", category_id: "cat-smoothies", category_name: "Smoothies",
      name: "Date & Tahini Shake",
      description: "Medjool dates, tahini, banana, almond milk & cinnamon",
      price: 190, calories: 320, protein: 8, carbs: 46, fat: 12,
      portion_size: 380, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: ["contains-nuts"],
      tags: [
        { slug: "vegan",        name: "Vegan",       tag_group: "diet",    color: "#5B7A3D" },
        { slug: "vegetarian",   name: "Vegetarian",  tag_group: "diet",    color: "#7E9C5C" },
        { slug: "gluten-free",  name: "Gluten-free", tag_group: "diet",    color: "#A6BE86" },
        { slug: "dairy-free",   name: "Dairy-free",  tag_group: "diet",    color: "#A6BE86" },
        { slug: "contains-nuts",name: "Nuts",        tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
    {
      id: "d12", category_id: "cat-juices", category_name: "Fresh Juices",
      name: "Pomegranate",
      description: "Cold-pressed pomegranate, nothing added",
      price: 160, calories: 150, protein: 2, carbs: 36, fat: 0,
      portion_size: 300, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: [],
      tags: [
        { slug: "vegan",      name: "Vegan",       tag_group: "diet", color: "#5B7A3D" },
        { slug: "vegetarian", name: "Vegetarian",  tag_group: "diet", color: "#7E9C5C" },
        { slug: "gluten-free",name: "Gluten-free", tag_group: "diet", color: "#A6BE86" },
        { slug: "dairy-free", name: "Dairy-free",  tag_group: "diet", color: "#A6BE86" },
      ],
      badges: [],
    },
    {
      id: "d13", category_id: "cat-juices", category_name: "Fresh Juices",
      name: "Carrot · Orange · Turmeric",
      description: "Cold-pressed carrot, orange, turmeric & black pepper",
      price: 150, calories: 130, protein: 2, carbs: 30, fat: 1,
      portion_size: 300, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegan", "vegetarian", "gluten-free", "dairy-free"],
      allergens: [],
      tags: [
        { slug: "vegan",      name: "Vegan",       tag_group: "diet", color: "#5B7A3D" },
        { slug: "vegetarian", name: "Vegetarian",  tag_group: "diet", color: "#7E9C5C" },
        { slug: "gluten-free",name: "Gluten-free", tag_group: "diet", color: "#A6BE86" },
        { slug: "dairy-free", name: "Dairy-free",  tag_group: "diet", color: "#A6BE86" },
      ],
      badges: [],
    },
    {
      id: "d14", category_id: "cat-coffee", category_name: "Coffee",
      name: "Cardamom Flat White",
      description: "Double ristretto, ground cardamom, silky milk",
      price: 130, calories: 120, protein: 6, carbs: 9, fat: 6,
      portion_size: 180, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegetarian"],
      allergens: ["contains-dairy"],
      tags: [
        { slug: "vegetarian",   name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-dairy",name: "Dairy",   tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [{ label: "Chef's pick", tone: "gold" }],
    },
    {
      id: "d15", category_id: "cat-coffee", category_name: "Coffee",
      name: "Mint Iced Latte",
      description: "Espresso, fresh mint, milk over ice",
      price: 140, calories: 110, protein: 5, carbs: 11, fat: 4,
      portion_size: 300, portion_unit: "ml",
      image_url: null, is_featured: false,
      diets: ["vegetarian"],
      allergens: ["contains-dairy"],
      tags: [
        { slug: "vegetarian",   name: "Vegetarian",tag_group: "diet",    color: "#7E9C5C" },
        { slug: "contains-dairy",name: "Dairy",   tag_group: "allergen",color: "#D2A24A" },
      ],
      badges: [],
    },
  ],
  bundles: [
    { tierCode: "SET-4",  label: "Manakish set of 4",  manakishCount: 4,  sauceCount: 1, discountPct: 10 },
    { tierCode: "SET-8",  label: "Manakish set of 8",  manakishCount: 8,  sauceCount: 2, discountPct: 15 },
    { tierCode: "SET-12", label: "Manakish set of 12", manakishCount: 12, sauceCount: 3, discountPct: 20 },
  ],
};
